ARG NODE_VERSION=lts-alpine
FROM node:${NODE_VERSION} AS build
WORKDIR /app
COPY package.json .

# Dependencies
RUN npm install
COPY nginx.conf .
COPY . /app

# Production Config
COPY config.prod.js /app/src/helpers/services/server.js

RUN npm run build

# Web Server
FROM nginx:stable-alpine-slim
COPY --from=build /app/build usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

#docker build -f Dockerfile.prod -t frontend .
#docker run -d -p 3000:80 --name frontend frontend