version: '3.9'

services:

  database:
    container_name: database
    image: postgres:14-alpine
    volumes:
      - postgres_talygapglobal:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=tasks
      - POSTGRES_PASSWORD=tasks
      - POSTGRES_DB=tasks
  talycapglobal:
    container_name: talycapglobal
    image: talycapglobal:latest
    environment:
      - DB_URL=jdbc:postgresql://database:5432/tasks
      - DB_USER=tasks
      - DB_PASSWORD=tasks
      - JPA_HIBERNATE_DDL_AUTO=update
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2024:2024"
    restart: always

volumes:
  postgres_talygapglobal: